### ISSUE TITLE
issues with bought  motorcycle and garage

### ISSUE THREAD

**Issue by therealnoskill** [Qbox-project/qb-vehicleshop#117]
### Summary

not possible to use motorcyles in garage. cant use lock/unloick

### Reproduction

go to vehicleshop
buy motorcycle and go into garage
take out vehicle and try to lock/unlock

not possible to use the bike anymore

### Expected behavior

fix the garage or vehicleshop

### Actual behavior

we cant use the garage with bikes

### Current Version

1.0.0

### Custom Resources

no

**Comment by therealnoskill** [comment]
it seems to be the vehiclelock function. after buy a motorcycle you cant use lock/unlock

**Comment by D4isDAVID** [comment]
Can't reproduce this issue anymore. Try using an updated version of qbx_vehiclekeys.
