### ISSUE TITLE
[BUG] RandomInt

### ISSUE THREAD

**Issue by mataskc** [Qbox-project/qb-vehicleshop#22]
### Summary

Cant buy vehicles

### Reproduction

1. Try to buy vehicle
2. Check server console

### Expected behavior

To buy a vehicle

### Actual behavior

Cant buy vehicle

### Additional context

When I buy a vehicle, this is what happens:
`[script:qbx-vehiclesh] SCRIPT ERROR: @qbx-vehicleshop/server.lua:89: attempt to call a nil value (field 'RandomInt')`

### Last Updated

today

### Custom Resources

none

### Resource Rename

no

**Comment by ChatDisabled** [comment]
Should be fixed with https://github.com/Qbox-project/qbx-vehicleshop/pull/24
