### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by iitzSamy** [Qbox-project/qb-vehicleshop#25]
### Summary

Unwanted purchase

### Reproduction

https://github.com/Qbox-project/qbx-vehicleshop/assets/70079085/fd8075cb-808c-46b1-984d-64273d53896d

### Expected behavior

that when you choose a car and buy it, you are awarded the one you chose

### Actual behavior

When you choose a car to buy, you end up buying the one that is on display at the beginning and not the one you chose when you bought it.

### Last Updated

today

### Custom Resources

ox_target (last version)

### Resource Rename

no

**Comment by mockdot** [comment]
Fixed in: #27
