### ISSUE TITLE
Vehicle won't despawn if player gets out from the vehicle during a test drive

### ISSUE THREAD

**Issue by SKITTLE6969** [Qbox-project/qb-vehicleshop#43]
### Summary

Vehicle won't despawn if player gets out from the vehicle during a test drive

### Reproduction

Go to PDM
Start a Test drive
Get out from vehicle

### Expected behavior

vehicle to be deleted and test drive timer to end

### Actual behavior

test drive timer continues and can be abused to not let the vehicle despawn

### Last Updated

11/17/23

### Custom Resources

all vanilla

### Resource Rename

no

**Comment by SKITTLE6969** [comment]
![image](https://github.com/Qbox-project/qbx_vehicleshop/assets/92496158/d64664c0-7280-47c6-9a89-34d794e83303)

**Comment by mafewtm** [comment]
The vehicle is supposed to remain for a certain period of time, no? Affording the player the allotted time to finish the test drive even if, for some reason, they step out of the car or get ejected out of the car? I don't think the vehicle should automatically despawn if they step out of the vehicle before the allotted time is up.

**Comment by Manason** [comment]
> The vehicle is supposed to remain for a certain period of time, no? Affording the player the allotted time to finish the test drive even if, for some reason, they step out of the car or get ejected out of the car? I don't think the vehicle should automatically despawn if they step out of the vehicle before the allotted time is up.

I think we should introduce a realism feature so you actually have to bring the vehicle back. And we have like a second timer for that; if not the police are called, and you get put on a blacklist for a configurable amount of time from test driving in the future.

**Comment by SKITTLE6969** [comment]
Adding realism is good but people used to abuse this and spawn alot of cars and use them for ciminal acitivities, if we can make it so that no matter what player does, the vehicle despawns after the time, im good with it! :D

**Comment by mafewtm** [comment]
Theres only so much we can do to deal with what server owners and staff should be doing before it takes away from the script itself.

**Comment by Manason** [comment]
I don't think gating this type of feature behind a config option hurts.

**Comment by dusan01** [comment]
Tested this, and the vehicle despawns after the time is over no matter if you are in the vehicle or out of the vehicle.
