### ISSUE TITLE
Add statebag for vehicle sales and gifts

### ISSUE THREAD

**Issue by solareon** [Qbox-project/qb-vehicleshop#51]
### The problem

Currently selling a vehicle after #50 pops up a dialog box on the recipients end to confirm/deny the sale. This isn't clean or nice for the user.

### Ideal solution

A solution using statebags where the prospective buyer/giftee would target the vehicle and make an offer through an input box and then the seller would also target the vehicle and then accept/decline the offer. This could be made further flexible by allowing multiple offers to exist on a vehicle and then providing the seller with a context menu or something of the sort to pick the offer.

**Comment by TonybynMp4** [comment]
Could also consider using NPWD's notification API for that 🤔 (as an option ofc)

**Comment by Manason** [comment]
I like this idea.

**Comment by TonybynMp4** [comment]
I'll try and add it then
