### ISSUE TITLE
Players not being sent back to dealership after test drive

### ISSUE THREAD

**Issue by ADRNALN** [Qbox-project/qb-vehicleshop#57]
### Summary

Players not being sent back to dealership after test drive

### Reproduction

When players test drive a vehicle and their test drive is over they're just left stranded in the middle of the street instead of being sent back to the dealership

### Expected behavior

Players should get sent back to the dealership

### Actual behavior

Player is left on the street

### Last Updated

Yesterday

### Custom Resources

N/A

### Resource Rename

qbx_vehicleshop

**Comment by mafewtm** [comment]
This is done on purpose.

**Comment by ADRNALN** [comment]
Why is that?

**Comment by mafewtm** [comment]
The player shouldn't have to be poofed back to the dealership. They take a test drive and are given an allotted time. It is up to them to return in the allotted time.

**Comment by jonezkti** [comment]
Why not make the test drive happen in its own location fe. the drift zone, then just make the player teleport back to where they started the test drive (the dealership) when the time runs out.

**Comment by Manason** [comment]
I'm in favor of having different test drive implementations controlled by like a config enum.

**Comment by Manason** [comment]
I believe this is now resolved with the latest commit. If someone wants to add additional implementation controlled by a config enum feel free to PR.
