### ISSUE TITLE
Vehicle ID not set on purchase

### ISSUE THREAD

**Issue by CarlBishop** [Qbox-project/qb-vehicleshop#71]
### Summary

Vehicle ID not set on purchase, this doesn't allow to park vehicle

### Reproduction

Due to new change on qbx_garages, vehicleshop must set vehicleid on purchase.

Actually this doen't happen so when someone try to park the vehicle we get the server side error: **owned vehicles must have vehicle ids**

### Expected behavior

We should be able to park the purchased vehicle

### Actual behavior

Ne vehicle id created on purchase

### Current Version

latest main branch

### Custom Resources

none

**Comment by artur-michalak** [comment]
The problem should no longer occur

**Comment by CarlBishop** [comment]
I didn't tested the fix. I will do this evening

**Comment by artur-michalak** [comment]
Any update?

**Comment by highpixudo** [comment]
still having this error

**Comment by artur-michalak** [comment]
Do you have the latest version of the resource?

**Comment by Manason** [comment]
This is where it's being set https://github.com/Qbox-project/qbx_vehicleshop/blob/main/server/main.lua#L244
